config/routes.rb
 Rails.application.routes.draw do
   resources :requests
    devise_for :users
    resources :movies do
      resources :reviews
    end
    root 'movies#index'
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/movie.rb
class Movie < ApplicationRecord
  # Associatyions-------------------
  has_one_attached :image
  has_many :reviews,dependent: :destroy

  # For average rating-----------------
  def average_rating
    if reviews.present?
      (reviews.average(:rating) || 0).to_f.round(2)
    else
      0
    end
  end
end

app/models/request.rb
class Request < ApplicationRecord
  validates :movie_name, uniqueness: true
  validates :movie_name, presence: true
  belongs_to :user
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :movie

  validates :comment, presence: true
  validates :rating, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :reviews
  has_many :requests
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /movies or /movies.json
  def index

    @movies = Movie.all

    @movies = Movie.all.sort_by { |movie| -movie.average_rating }

    if params[:search].present?
      @movies = @movies.select { |movie| movie.name.downcase.include?(params[:search].downcase) }
    end

    if params[:from_date].present? && params[:to_date].present?
      from_date = Date.parse(params[:from_date])
      to_date = Date.parse(params[:to_date])
      @movies = Movie.where(release_date: from_date.beginning_of_day..to_date.end_of_day)
    end

  end

  # GET /movies/1 or /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies or /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to movie_url(@movie), notice: "Movie was successfully created." }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1 or /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to movie_url(@movie), notice: "Movie was successfully updated." }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1 or /movies/1.json
  def destroy
    @movie.destroy

    respond_to do |format|
      format.html { redirect_to movies_url, notice: "Movie was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def movie_params
      params.require(:movie).permit(:name, :release_date,  :image)
    end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_request, only: %i[ show edit update destroy ]

  # GET /requests or /requests.json
  def index
    @requests = Request.all
  end

  # GET /requests/new
  def new
    @request = Request.new
  end

  # GET /requests/1/edit
  def edit
  end

  # POST /requests or /requests.json
  def create
    @request = Request.new(request_params)
    if user_signed_in?
      @request.user = current_user
    end
    respond_to do |format|
      if @request.save
        format.html { redirect_to requests_path, notice: "Request was successfully created." }
        format.json { render :show, status: :created, location: @request }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /requests/1 or /requests/1.json
  def update
    respond_to do |format|
      if @request.update(request_params)
        format.html { redirect_to requests_path(@request), notice: "Request was successfully updated." }
        format.json { render :show, status: :ok, location: @request }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requests/1 or /requests/1.json
  def destroy
    @request.destroy

    respond_to do |format|
      format.html { redirect_to requests_path, notice: "Request was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_request
      @request = Request.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def request_params
      params.require(:request).permit(:movie_name, :user_id)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: %i[ show edit update destroy ]
  before_action :get_movie
  # GET /reviews or /reviews.json
  def index
    @reviews = @movie.reviews
  end

  # GET /reviews/1 or /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = @movie.reviews.build
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews or /reviews.json
  def create
    @review = @movie.reviews.build(review_params)
    if user_signed_in?
      @review.user = current_user
    end
    respond_to do |format|
      if @review.save
        format.html { redirect_to movie_reviews_path(@movie), notice: "Review was successfully created." }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1 or /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to movie_reviews_path(@movie), notice: "Review was successfully updated." }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1 or /reviews/1.json
  def destroy
    @review.destroy

    respond_to do |format|
      format.html { redirect_to movie_reviews_path(@movie), notice: "Review was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

  def get_movie
    @movie = Movie.find(params[:movie_id])
  end


  # Only allow a list of trusted parameters through.
    def review_params
      params.require(:review).permit(:comment, :rating, :user_id, :movie_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieReviewSystemApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  </head>

  <body>
  <div class="navbar" style="height: 60px;">
    <%= link_to "Home", root_path,class: "nav-link", class: "btn btn-outline-light"%>
    <% if current_user %>
      <div class="greet">
      <span class="greeting">Hello, <%= current_user.email %></span>
      </div>
        <%= link_to "Requests", requests_path, class: "btn btn-outline-light" %>
        <%= link_to "Edit Profile", edit_user_registration_path, class: "btn btn-outline-light" %>
        <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-outline-light" %>
    <% else %>
      <%= link_to "Sign In", new_user_session_path, class: "nav-link", class: "btn btn-outline-light" %>
      <%= link_to "Sign Up", new_user_registration_path, class: "nav-link", class: "btn btn-outline-light" %>
    <% end %>
  </div>

  <%= yield %>
  </body>
</html>

<style>
    .greet {
        border: 1px solid white; /* Add a white border */
        padding: 8px; /* Add padding for spacing inside the box */
        border-radius: 5px; /* Add rounded corners if desired */
        display: inline-block; /* Ensure it doesn't take up the entire width */
        color: white; /* Set the text color to white */
    }
</style>

app/views/movies/_form.html.erb
<div class= "box-container" align="center">
  <div id="<%= dom_id movie %>">
<%= form_with(model: movie) do |form| %>
  <% if movie.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
        <% movie.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, "<strong>Name</strong>".html_safe, style: "display: block;" %>
    <%= form.text_field :name %>
  </div>
<br>
  <div>
    <%= form.label :release_date, "<strong>Release date</strong>".html_safe, style: "display: block" %>
    <%= form.date_field :release_date %>
  </div>
<br>
<!--  <div class="field">-->
    <%#= form.label :image, "<strong>Image</strong>".html_safe %>
    <%#= form.file_field :image %>
<!--  </div>-->
<br>
  <div>
    <%= form.submit class: "btn btn-primary btn-sm" %>
  </div>
<% end %>
  </div>
</div>


<style>
    /* Define styles for the container */
    .box-container {
        width: 300px; /* Set the width of the box */
        height: 350px; /* Set the height of the box */
        border: 1px solid black; /* Add a border */
        padding: 20px; /* Add some padding inside the box */
        margin: 20px; /* Add margin to create space between containers */
        background-color: rgb(224,255,255,0.7);
        border-radius: 10px; /* Add rounded corners */
        color: #000000;
        align-content: center;
        font-size: 17px;

    }
</style>

app/views/movies/_movie.html.erb
<div class= "box-container" align="center">
  <div id="<%= dom_id movie %>">
    <p>
      <strong>Name : </strong>
      <%= movie.name %>
    </p>

    <p>
      <strong>Release date : </strong>
      <%= movie.release_date %>
    </p>

    <p>
    <%# if movie.image.attached? %>
      <%#= image_tag movie.image, style: "max-width: 200px; max-height: 150px; "%>
    <%# end %>
    </p>
    <p>
      <strong>Rating:</strong>
      <%= movie.average_rating %>
      <%='⭐' %>
    </p>
    <%= link_to 'View Reviews', movie_reviews_path(movie), class: "btn btn-primary btn-sm" %>
    <% if current_user.id==1 %>
      <%= link_to "Show this movie", movie_path(movie), class: "btn btn-info  btn-sm" %>
    <% end %>
  </div>
</div>


<style>
    /* Define styles for the container */
    .box-container {
        width: 300px; /* Set the width of the box */
        height: 220px; /* Set the height of the box */
        border: 1px solid black; /* Add a border */
        padding: 20px; /* Add some padding inside the box */
        margin: 20px; /* Add margin to create space between containers */
        float: left; /* For the movie box to appear side by side */
        background-color: rgb(224,255,255,0.7);
        border-radius: 10px; /* Add rounded corners */
        color: #000000;
        align-content: center;
        font-size: 17px;

    }
</style>

app/views/movies/edit.html.erb
<div align="center">
<% if current_user.id==1 %>
  <br>
  <br>
  <br>
  <div class="color">
    <h4>Editing movie</h4>
  </div>
  <%= render "form", movie: @movie %>
  <br>
  <div>
  <%= link_to "Show this movie", @movie, class: "btn btn-info btn-sm" %> |
  <%= link_to "Back to movies", movies_path, class: "btn btn-info btn-sm" %>
  </div>
  <%else %>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
  <div class="color">
  <h4>You have no access to edit</h4>
    <br>
  </div>
  <%= link_to "Back to movies", movies_path, class: "btn btn-info btn-sm" %>
<% end %>
</div>
<style>
    .color
    {
        color: #F7F7F7;
    }
</style>

app/views/movies/index.html.erb
<div align="center">
  <p style="color: green"><%= notice %></p>
  <div class="movies">
    <br>
    <h1 align="center">Movies</h1>
  </div>
  <%= form_tag(movies_path, method: 'get') do %>
    <%= text_field_tag :search, params[:search], placeholder: 'Search by movie name'%>
    <%= submit_tag 'Search', class: "btn btn-secondary btn-sm" %>
    <%= link_to 'Clear', root_path, class: "btn btn-secondary btn-sm" %>
  <% end %>
<br>
  <%= form_tag movies_path, method: :get do %>
    <div align="center">
      <%= label_tag 'from_date', 'From Date:', style: 'color: white;' %>
      <%= date_field_tag 'from_date', params[:from_date], class: 'datepicker'%>

      <%= label_tag 'to_date', 'To Date:', style: 'color: white;' %>
      <%= date_field_tag 'to_date', params[:to_date], class: 'datepicker'%>
      <%= submit_tag 'Apply Filter', class: "btn btn-secondary btn-sm" %>
      <%= link_to 'Clear filter', root_path, class: "btn btn-secondary btn-sm" %>
  <% end %>
  <div id="movies" class="clearfix">
    <% @movies.each do |movie| %>
      <%= render movie %>
    <% end %>
  </div>

  <% if current_user.id==1 %>
    <br>
    <%= link_to "Add new movie", new_movie_path, class: "btn btn-info  btn-block" %>
  <% end %>
</div>
</div>
<style>

.clearfix::after {
content: "";
display: table;
clear: both;
}

.movies
 {
     color: #F7F7F7;

 }

</style>

app/views/movies/new.html.erb
<div align="center">
  <% if current_user.id==1 %>
  <br>
  <br>
  <br>
  <div class="color">
    <h4>New movie</h4>
  </div>
  <%= render "form", movie: @movie %>
    <br>
    <div>
  <%= link_to "Back to movies", movies_path, class: "btn btn-info btn-sm" %>
    <% else %>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <div class="color">
    <h4>You don't have access for this</h4>
    </div>
    <br>
    <br>
      <%= link_to "Back to movies", movies_path, class: "btn btn-info btn-sm" %>
  <% end %>
  </div>
</div>


<style>
    .color
    {
        color: #F7F7F7;
    }
</style>

app/views/movies/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @movie %>
<% if current_user.id==1 %>
    <%= link_to "Edit this movie", edit_movie_path(@movie), class: "btn btn-info  btn-sm"  %>
    <br>
    <br>
    <%= button_to "Destroy this movie", @movie, method: :delete, class: "btn btn-info  btn-sm"  %>
<% end %>
<br>
<%= link_to "Back to movies", movies_path, class: "btn btn-info  btn-sm"  %>

app/views/requests/_form.html.erb
<div align="center">

<%= form_with(model: request) do |form| %>

  <% if request.errors.any? %>
      <div class="error-box">
      <h8><%= pluralize(request.errors.count, "error") %> prohibited this request from being saved:</h8>

      <ul>
        <% request.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
    <div class="box-container">
  <div>
    <%= form.label :movie_name, style: "display: block" %>
    <%= form.text_field :movie_name %>
  </div>
<br>
  <div>
    <%= form.submit class: "btn btn-success btn sm"%>
  </div>
<% end %>
</div>
</div>

<style>
    /* Define styles for the container */
    .box-container {
        width: 300px; /* Set the width of the box */
        height: 150px; /* Set the height of the box */
        border: 1px solid black; /* Add a border */
        padding: 20px; /* Add some padding inside the box */
        margin: 20px; /* Add margin to create space between containers */
         /* For the movie box to appear side by side */
        background-color: rgb(224,255,255,0.7);
        border-radius: 10px; /* Add rounded corners */
        color: #000000;
        align-content: center;
        font-size: 17px;

    }

    .error-box
    {
        position: absolute;
        top: 80px;
        right: 10px;
        background-color: red;
        padding: 5px;
        color: white;
        width:300px;
        border-radius: 5px;
    }
</style>

app/views/requests/_request.html.erb
<div id="<%= dom_id request %>">
  <p>
    <%= request.movie_name %>
    <br>
    <strong>Requested by :</strong>
    <% if request.user %>
      <%= request.user.email %>
    <% else %>
      User not available
    <% end %>
  </p>

</div>

app/views/requests/edit.html.erb
<h1>Editing request</h1>

<%= render "form", request: @request %>

<br>

<div>
  <%= link_to "Show this request", @request %> |
  <%= link_to "Back to requests", requests_path %>
</div>

app/views/requests/index.html.erb
<div style="text-align: center;">
  <div>
    <p style="color: green;"><%= notice %></p>
<br>
    <br>
    <div class="color">
    <h4>Requests</h4>
    </div>
    <div class="table-container">
    <table class="table table-secondary">
      <thead>
      <tr>
        <th>Movies Requested</th>
      </tr>
      </thead>
      <tbody>
      <% @requests.each do |request| %>
        <tr>
          <td><%= render request %></td>
          <% if current_user.id==1 %>
          <td><%= button_to "Delete this request", request, method: :delete %></td>
            <%end %>
        </tr>
      <% end %>
      </tbody>
    </table>
    </div>
    <div class="color">
        <h6>If the movie you want is not in the request list, </h6>
    </div>
    <%= link_to "Request movie", new_request_path, class: "btn btn-info btn sm" %>
    <%= link_to "Back", root_path, class: "btn btn-info btn sm"  %>
  </div>
</div>

<style>
    .color
    {
        color: #F7F7F7;
    }
    .table-container {
        width: 80%; /* Set the desired width for the table container */
        margin: 0 auto; /* Center the table container horizontally */
    }
</style>

app/views/requests/new.html.erb
<div align="center">
  <div class="color">
    <br>
    <br>
    <br>
<h4>New request</h4>

<%= render "form", request: @request %>

<br>

<div>
  <%= link_to "Back to requests", requests_path, class: "btn btn-info btn sm" %>
</div>
</div>
</div>
<style>
    .color
    {
        color: #F7F7F7;
    }
</style>

app/views/reviews/_form.html.erb
<%= form_with(model: [@movie, review]) do |form| %>
  <% if review.errors.any? %>
    <div class="error-box">
      <h8> prohibited this review from being saved:</h8>

      <ul>
        <% review.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <br>
  <br>
  <div class= "box-container">
  <div>
    <%= form.label :comment, style: "display: block" %>
    <%= form.text_area :comment, style: 'border-radius: 7px; ' %>
  </div>
<br>
  <div class="field">
    <%= form.radio_button :rating , 1 %>
    <%= form.label :one , '⭐1', :value=> 1 %>

    <%= form.radio_button :rating , 2 %>
    <%= form.label :two , '⭐2', :value=> 2 %>

    <%= form.radio_button :rating , 3 %>
    <%= form.label :three , '⭐3', :value=> 3 %>

    <%= form.radio_button :rating , 4 %>
    <%= form.label :four , "⭐4", :value=> 4 %>

    <%= form.radio_button :rating , 5 %>
    <%= form.label :five , "⭐5", :value=> 5 %>
  </div>
<br>
  <div>
    <%= form.submit class: "btn btn-success btn sm" %>
  </div>
  </div>
<% end %>



<style>
    /* Define styles for the container */
    .box-container {
        width: 400px; /* Set the width of the box */
        height: 250px; /* Set the height of the box */
        overflow: auto;        border: 1px solid black; /* Add a border */
        padding: 20px; /* Add some padding inside the box */
        margin: 20px; /* Add margin to create space between containers */
        border-radius: 10px; /* Add rounded corners */
        background-color: rgb(224,255,255,0.7);
        color: #000000;
        font-size: 15px;
        position: relative;
    }

.error-box
{
    position: absolute;
    top: 80px;
    right: 10px;
    background-color: red;
    padding: 5px;
    color: white;
    width:400px;
    border-radius: 5px;
}

</style>

app/views/reviews/_review.html.erb
<div class= "box-container">
<div id="<%= dom_id review %>">
  <p>
    <strong>Comment:</strong>
    <%= review.comment %>
  </p>

  <p>
    <strong>Rating:</strong>
    <%= review.rating %>
    <%='⭐' %>
  </p>
<p>
  <strong>Review posted by:</strong>
  <%= review.user.email %>
</p>
  <% if current_user == review.user %>
    <div class="btn-group">
      <%= link_to "Edit review", edit_movie_review_path(@movie, review), class: "btn btn-primary btn-sm" %>
      <span class="btn-gap"></span> <!-- Add a gap with a span element -->
      <%= button_to "Delete review", movie_review_path(@movie, review), method: :delete, class: "btn btn-danger btn-sm" %>
    </div>
  <% end %>

</div>
</div>

<style>
    /* Define styles for the container */
    .box-container {
        width: 400px; /* Set the width of the box */
        height: 200px; /* Set the height of the box */
        border: 1px solid black; /* Add a border */
        padding: 20px; /* Add some padding inside the box */
        margin: 20px; /* Add margin to create space between containers */
        border-radius: 10px; /* Add rounded corners */
        background-color: rgb(224,255,255,0.8);
        color: #000000;
        font-size: 15px;
    }

    .btn-gap {
        margin-left: 10px; /* Adjust the margin size as needed */
    }

</style>

app/views/reviews/edit.html.erb
<div align="center">
  <br>
  <br>
  <br>
  <div class="reviews">
<h3>Editing review</h3>
  </div>
<%= render "form", review: @review %>

<br>

<div>
  <%= link_to "Back to reviews", movie_reviews_path(@movie), class: "btn btn-info  btn-block"  %>
</div>
</div>

<style>
    .reviews
    {
        color: #F7F7F7;
    }
</style>

app/views/reviews/index.html.erb
<p style="color: green"><%= notice %></p>
<div align="center">
  <div class="reviews">
  <p>
    <br>
    <strong >Reviews for:</strong>
    <%= @movie.name %>
  </p>
  </div>
  <div id="reviews">
    <% @reviews.each do |review| %>
      <%= render review %>
    <% end %>
  </div>

  <%= link_to "Give your review", new_movie_review_path, class: "btn btn-info  btn-block" %>
  <%=link_to "Back", movies_path(@movie), class: "btn btn-info  btn-block" %>
  <br>
</div>

<style>
  .reviews
  {
  color: #F7F7F7;
  }
</style>

app/views/reviews/new.html.erb
<div align="center">
  <br>
  <br>
  <br>
  <div class="reviews">
<h3>New review</h3>

<%= render "form", review: @review %>

<br>

<div>
  <%= link_to "Back to reviews", movie_reviews_path(@movie), class: "btn btn-info  btn-block" %>
</div>
  </div>
</div>
<style>
    .reviews
    {
        color: #F7F7F7;
    }
</style>

app/views/reviews/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @review %>

<div>
  <%= link_to "Edit this review", edit_movie_review_path(@review) %> |
  <%= link_to "Back to reviews", movie_reviews_path %>

  <%= button_to "Destroy this review", movie_review_path(@review), method: :delete %>
</div>